from fastapi import APIRouter, HTTPException, BackgroundTasks
from models.report_models import MedicalReport
from services.report_generator_service import report_generator
from pydantic import BaseModel
from typing import Dict, Any, Optional
import httpx
import json

router = APIRouter(prefix="/api/medical-report", tags=["Medical Report"])

# In-memory store for doctor actions
# Key: user_id, Value: Dict (action details)
doctor_actions: Dict[str, Dict[str, Any]] = {}

class DoctorAction(BaseModel):
    doctor_id: str
    action_type: str
    note: Optional[str] = None
    timestamp: str

@router.post("/{user_id}", response_model=MedicalReport)
async def generate_medical_report(user_id: str):
    """
    Generates a comprehensive clinical decision support report 
    analyzing 90 days of patient data using Gemini 1.5 Pro.
    """
    try:
        report = await report_generator.generate_report(user_id)
        return report
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/{user_id}/email")
async def email_medical_report(user_id: str, background_tasks: BackgroundTasks):
    """
    Generates the report and sends it to the Doctor's Email Dashboard (Port 8020).
    """
    try:
        # 1. Generate Report
        report = await report_generator.generate_report(user_id)
        
        # 2. Format HTML Body for Email with Action Buttons
        # Note: We use absolute URLs for localhost to link back to Janani API from the Email App's context
        # In a real app, these would be deep links or API calls via the dashboard's backend.
        # Here we embed client-side JS in the email body that the Dashboard will render.
        
        html_body = f"""
        <h2>Clinical Alert: {report.patient_metadata.risk_factors[0] if report.patient_metadata.risk_factors else 'High Risk Pregnancy'}</h2>
        <p><strong>Patient ID:</strong> {user_id}</p>
        <p><strong>Gestational Age:</strong> {report.patient_metadata.gestational_age} Weeks</p>
        
        <div style="background-color: #fee2e2; padding: 15px; border-radius: 5px; border-left: 5px solid #dc2626; margin: 20px 0;">
            <h3 style="margin-top:0; color: #dc2626;">⚠️ {report.risk_stratification.current_risk}</h3>
            <p><strong>Chief Concern:</strong> {report.chief_concern.data_derived}</p>
        </div>

        <h3>Key Findings</h3>
        <ul>
            {''.join([f"<li>{p.metric}: {p.clinical_significance}</li>" for p in report.temporal_patterns])}
        </ul>

        <h3>Recommendations</h3>
        <ul>
            {''.join([f"<li><strong>{r.type.upper()}:</strong> {r.content}</li>" for r in report.recommendations])}
        </ul>
        
        <div style="margin-top: 30px; padding: 20px; background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px;">
            <h3 style="margin-top:0; color: #0284c7;">👨‍⚕️ Doctor Actions</h3>
            <p>Select an action to update the patient's care plan instantly:</p>
            <div style="display: flex; gap: 10px; flex-wrap: wrap;">
                <button onclick="sendDoctorAction(this, '{user_id}', 'approve_admission', 'Admit for PET Profile')" 
                        style="background: #22c55e; color: white; border: none; padding: 10px 15px; border-radius: 5px; cursor: pointer; font-weight: bold;">
                    ✅ Approve Admission
                </button>
                <button onclick="sendDoctorAction(this, '{user_id}', 'prescribe_meds', 'Start Labetalol + MgSO4')" 
                        style="background: #eab308; color: white; border: none; padding: 10px 15px; border-radius: 5px; cursor: pointer; font-weight: bold;">
                    💊 Prescribe Meds
                </button>
                <button onclick="sendDoctorAction(this, '{user_id}', 'request_call', 'Urgent Call Requested')" 
                        style="background: #3b82f6; color: white; border: none; padding: 10px 15px; border-radius: 5px; cursor: pointer; font-weight: bold;">
                    📞 Request Call
                </button>
            </div>
        </div>

        <hr>
        <p><small>Generated by Janani AI Clinical Decision Support</small></p>
        """

        # 3. Send to Email App
        background_tasks.add_task(send_email_to_dashboard, html_body)
        
        return {"status": "sending", "message": "Report is being sent to the doctor's dashboard."}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/{user_id}/doctor-action")
async def receive_doctor_action(user_id: str, action: DoctorAction):
    """
    Receives an action/instruction from the doctor (via Email Dashboard).
    """
    print(f"Received Doctor Action for {user_id}: {action}")
    doctor_actions[user_id] = action.dict()
    return {"status": "received", "action": action.dict()}

@router.get("/{user_id}/doctor-action")
async def get_doctor_action(user_id: str):
    """
    Polling endpoint for Janani UI to check for new doctor instructions.
    """
    if user_id in doctor_actions:
        action = doctor_actions[user_id]
        # Optional: Clear after reading if we want "one-time" alerts, 
        # but for state persistence let's keep it or manage read state.
        # For this demo, we'll keep it so the UI can show "Latest Status".
        return {"has_action": True, "action": action}
    return {"has_action": False}

async def send_email_to_dashboard(html_body: str):
    email_payload = {
        "sender": "Janani AI <alerts@janani.ai>",
        "subject": "URGENT: Preeclampsia Alert - Patient Rahima",
        "body": html_body,
        "priority": "high"
    }
    
    async with httpx.AsyncClient() as client:
        try:
            from config import settings
            await client.post(f"{settings.medimail_service_url}/api/receive-email", json=email_payload)
            print("Successfully sent email to dashboard")
        except Exception as e:
            print(f"Failed to send email: {e}")
